-- Student Billing Premium module: MySQL (MariaDB) install script
-- Executed on module activation (Modules.php > School > Configuration > Modules).
-- Idempotent: safe to re-run (CREATE TABLE IF NOT EXISTS).

SET default_storage_engine=InnoDB;

CREATE TABLE IF NOT EXISTS billing_monthly_fees (
	ID int(11) NOT NULL AUTO_INCREMENT,
	SCHOOL_ID int(11) NOT NULL,
	SYEAR decimal(4,0) NOT NULL,
	TITLE varchar(255) NOT NULL,
	AMOUNT decimal(14,2) NOT NULL,
	DUE_DAY int(11) NOT NULL DEFAULT 5,
	GRADE_ID int(11) NOT NULL DEFAULT 0,
	ACTIVE varchar(1) NOT NULL DEFAULT 'Y',
	CREATED_AT timestamp NULL DEFAULT current_timestamp(),
	UPDATED_AT timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
	PRIMARY KEY (ID),
	KEY SCHOOL_ID (SCHOOL_ID),
	KEY SYEAR (SYEAR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_monnify_transactions (
	ID int(11) NOT NULL AUTO_INCREMENT,
	SCHOOL_ID int(11) NOT NULL,
	SYEAR decimal(4,0) NOT NULL,
	STUDENT_ID int(11) NOT NULL,
	PAYMENT_REFERENCE varchar(100) NOT NULL,
	TRANSACTION_REFERENCE varchar(100) DEFAULT NULL,
	AMOUNT decimal(14,2) NOT NULL,
	CURRENCY varchar(3) NOT NULL DEFAULT 'NGN',
	STATUS varchar(20) NOT NULL DEFAULT 'PENDING',
	PAYMENT_METHOD varchar(50) DEFAULT NULL,
	PAYMENT_DESCRIPTION text DEFAULT NULL,
	BILLING_PAYMENT_ID int(11) DEFAULT NULL,
	CREATED_AT timestamp NULL DEFAULT current_timestamp(),
	UPDATED_AT timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
	PRIMARY KEY (ID),
	UNIQUE KEY PAYMENT_REFERENCE (PAYMENT_REFERENCE),
	KEY SCHOOL_ID (SCHOOL_ID),
	KEY SYEAR (SYEAR),
	KEY STUDENT_ID (STUDENT_ID),
	KEY STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sbp_webhook_log (
	ID int(11) NOT NULL AUTO_INCREMENT,
	EVENT_TYPE varchar(100) DEFAULT NULL,
	PAYMENT_REFERENCE varchar(100) DEFAULT NULL,
	TRANSACTION_REFERENCE varchar(100) DEFAULT NULL,
	STATUS varchar(50) DEFAULT NULL,
	SOURCE_IP varchar(45) DEFAULT NULL,
	PAYLOAD text DEFAULT NULL,
	CREATED_AT timestamp NULL DEFAULT current_timestamp(),
	PRIMARY KEY (ID),
	KEY PAYMENT_REFERENCE (PAYMENT_REFERENCE),
	KEY STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
